### ISSUE TITLE
[BUG] This MGFX effect was built for a different platform!

### ISSUE THREAD

**Issue by meniku** [augustozanellato/MonoGameUniversalEffects#1]
thanks for the awesome tool!
I'm running your project on the latest OSX Catalina and the latest Monogame development branch.

However when I run my game I'm getting the following error when the shader is loaded:

> This MGFX effect was built for a different platform!

apparently the `Profile` that is being tried to be loaded is set to `1`, while the expected `Profile` for my platform would be `0` (as defined by `Shader.OpenGL.cs`)

Do you have any hints for me?

**Comment by augustozanellato** [comment]
Luckily I have an hackintosh on Catalina, tomorrow I’ll investigate the issue!

**Comment by augustozanellato** [comment]
Have you checked that your mgcb file is set to “Platform: OpenGL”? 
If that’s the case, would you mind sharing with me the mgcb file? I don’t need the linked assets because I’ll just replace them with mock files

**Comment by meniku** [comment]
aha! yes that was it - it was set to Windows. It worked for all the other assets so I didn't expect such a setting there.

Thanks a lot!

**Comment by augustozanellato** [comment]
Anyways I found a bug in the server part, if you run `vagrant destroy; vagrant up;` you should get the latest version which will compile shaders fine if you set `Platform: MacOSX` inside you mgcb file.
