### ISSUE TITLE
[BUG] MonoGameUniversalEffects.Server always consuming 50% of the VMs CPU

### ISSUE THREAD

**Issue by meniku** [augustozanellato/MonoGameUniversalEffects#3]
The process, which apparently is the server backend for receiving the Shader Compilation Requests, is always spinning the CPU to it's max, also when there are currently no requests being processed.

I suspect it's because of that loop ( I didn't debug )
```
				while (true)
				{
					//Do nothing
				}
```
maybe just putting a sleep in there could already help

**Comment by augustozanellato** [comment]
Published beta3 which fixed both this and implements #2, just run `vagrant destroy; vagrant up` in the directory where you have the Vagrantfile

**Comment by meniku** [comment]
works perfectly! thanks!
